### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by flyflamemcpe** [theguyspublic/Minecraft-Appeals#1]
- [x] I admit to being guilty for this ban.
- [x] I understand that if my ban appeal is denied i will need to wait an additional 1 week to reappeal.
- [x] I understand that if my ban appeal is escalated there will be a longer delay.

**What is the reasoning for your ban?**
john

**Why should you be unbanned?**
jacob

**Please send a screenshot of your punishment**
jingleheimerschmidt

**What server were you banned on?**
- [x] KitPvP
- [ ] hub-1
- [ ] Survival
- [ ] event-a

Thank you for submitting an appeal. Please know that submitting multiple appeals will result in a block of the appeal system.

**Comment by FrozenHyper** [comment]
Denied. Obvious joke appeal.
